### ISSUE TITLE
Download speed

### ISSUE THREAD

**Issue by kumarnipun** [Jayapraveen/INE-courses-downloader#4]
Hi Jayapraveen, 

Download speed with is if very slow. and also when it download it also don't show download speed and progress. Request you can you fix it.

Thanks

**Comment by kumarnipun** [comment]
Download speed is very very slow

**Comment by kumarnipun** [comment]
Hi Jayapraveen,

Request you to please reply.

**Comment by Jayapraveen** [comment]
Hello @kumarnipun ,
Download speed is relatively dependent on your bandwidth, your location from the nearest cdn of the site's and the rate limiting from the server. There are few checks in the script in order to verify if the downloaded content is of error free, the checks might require additional bandwidth if there are connection issues. If the script is hogging memory or is cpu intensive, please do raise a issue with logs and needed information for troubleshooting.
